"use client";
import { useEffect, useState } from "react";

const css = `
:root{--font-display:'Instrument Serif',Georgia,serif;--font-body:'Inter',-apple-system,sans-serif;--ease:cubic-bezier(.22,1,.36,1);--max-w:1080px;--nav-h:64px}
[data-mode="personal"]{--bg:#2b2a24;--bg-alt:#32312a;--bg-surface:#3a3930;--text-1:#f2ede4;--text-2:#b5ad9e;--text-3:#7a7468;--accent:#5a7a5a;--accent-dim:rgba(90,122,90,0.1);--border:rgba(255,255,255,0.08);--nav-bg:rgba(43,42,36,0.92);--cta-bg:#5a7a5a;--cta-fg:#f2ede4}
[data-mode="enterprise"]{--bg:#fafaf8;--bg-alt:#f4f4f1;--bg-surface:#eeeee9;--text-1:#18181b;--text-2:#52525b;--text-3:#a1a1aa;--accent:#1e3a5f;--accent-dim:rgba(30,58,95,0.06);--border:rgba(0,0,0,0.06);--nav-bg:rgba(250,250,248,0.9);--cta-bg:#1e3a5f;--cta-fg:#fff}
*{margin:0;padding:0;box-sizing:border-box}html{scroll-behavior:smooth}body{font-family:var(--font-body);background:var(--bg);color:var(--text-1);-webkit-font-smoothing:antialiased;transition:background .5s var(--ease),color .5s var(--ease);overflow-x:hidden}
nav{position:fixed;top:0;left:0;right:0;height:var(--nav-h);display:flex;align-items:center;justify-content:space-between;padding:0 clamp(16px,4vw,40px);background:var(--nav-bg);backdrop-filter:blur(24px);-webkit-backdrop-filter:blur(24px);z-index:100;border-bottom:1px solid var(--border);transition:all .5s var(--ease)}
.logo{font-family:var(--font-display);font-size:1.3rem;color:var(--text-1);text-decoration:none;transition:color .5s var(--ease)}
.pill{display:flex;background:var(--bg-surface);border-radius:99px;padding:3px;gap:2px;transition:background .5s var(--ease)}.pill button{padding:6px 18px;border:none;border-radius:99px;font-family:var(--font-body);font-size:.82rem;font-weight:600;cursor:pointer;transition:all .3s var(--ease);color:var(--text-3);background:transparent}.pill button.on{background:var(--cta-bg);color:var(--cta-fg)}
.nav-btn{padding:8px 22px;border-radius:99px;border:none;font-family:var(--font-body);font-size:.82rem;font-weight:600;background:var(--cta-bg);color:var(--cta-fg);cursor:pointer;text-decoration:none;transition:all .2s var(--ease)}.nav-btn:hover{opacity:.85;transform:translateY(-1px)}
.hero{text-align:center;padding:calc(var(--nav-h) + 72px) 24px 40px}.hero h1{font-family:var(--font-display);font-size:clamp(2.6rem,6vw,4.4rem);font-weight:400;line-height:1.08;letter-spacing:-.03em;max-width:700px;margin:0 auto 20px;text-wrap:balance;animation:fu .7s var(--ease) both}.hero h1 em{font-style:italic;color:var(--accent);transition:color .5s var(--ease)}.hero-sub{font-size:clamp(.95rem,1.6vw,1.1rem);color:var(--text-2);max-width:500px;margin:0 auto 32px;line-height:1.6;transition:color .5s var(--ease);animation:fu .7s var(--ease) .1s both}.hero-ctas{display:flex;gap:12px;justify-content:center;align-items:center;margin-bottom:48px;animation:fu .7s var(--ease) .2s both}
.btn-primary{display:inline-flex;align-items:center;padding:13px 30px;border-radius:99px;border:none;font-family:var(--font-body);font-size:.92rem;font-weight:600;background:var(--cta-bg);color:var(--cta-fg);cursor:pointer;text-decoration:none;transition:all .2s var(--ease)}.btn-primary:hover{opacity:.88;transform:translateY(-1px)}
.btn-text{font-size:.9rem;color:var(--text-2);text-decoration:none;border:none;border-bottom:1px solid transparent;transition:all .2s var(--ease);padding:13px 8px;background:none;cursor:pointer;font-family:var(--font-body);font-weight:500}.btn-text:hover{color:var(--text-1);border-bottom-color:var(--text-3)}
@keyframes fu{from{opacity:0;transform:translateY(18px)}to{opacity:1;transform:none}}
.phone-wrap{display:flex;justify-content:center;animation:pi 1s var(--ease) .3s both}@keyframes pi{from{opacity:0;transform:translateY(24px) scale(.97)}to{opacity:1;transform:none}}
.iphone{width:270px;height:585px;background:#1a1a1a;border-radius:42px;padding:10px;position:relative;box-shadow:0 40px 80px rgba(0,0,0,.35),0 0 0 1px rgba(255,255,255,.06) inset;transition:transform .4s var(--ease)}.iphone:hover{transform:translateY(-4px)}.iphone::before{content:'';position:absolute;right:-2px;top:140px;width:3px;height:52px;background:#2a2a2a;border-radius:0 2px 2px 0}.iphone::after{content:'';position:absolute;left:-2px;top:120px;width:3px;height:30px;background:#2a2a2a;border-radius:2px 0 0 2px}
.iphone-screen{width:100%;height:100%;background:#F2F2F7;border-radius:34px;overflow:hidden;display:flex;flex-direction:column;position:relative}.di{position:absolute;top:10px;left:50%;transform:translateX(-50%);z-index:20;width:86px;height:25px;background:#000;border-radius:16px}.ios-bar{display:flex;justify-content:space-between;align-items:center;padding:14px 22px 0;font-size:11px;font-weight:600;color:#000;min-height:44px;position:relative;z-index:10;background:#F2F2F7;flex-shrink:0}.ios-time{font-size:12px;font-weight:700}.ios-icons{display:flex;gap:4px;align-items:center}.ios-sig{display:flex;gap:1.5px;align-items:flex-end}.ios-sig span{display:block;width:3px;border-radius:.5px;background:#000}.ios-sig span:nth-child(1){height:3px}.ios-sig span:nth-child(2){height:5px}.ios-sig span:nth-child(3){height:7px}.ios-sig span:nth-child(4){height:9px}.ios-bt{display:flex;align-items:center;gap:1px}.ios-bt-b{width:19px;height:8.5px;border:1.2px solid rgba(0,0,0,.35);border-radius:2.5px;position:relative;overflow:hidden}.ios-bt-f{position:absolute;left:1px;top:1px;bottom:1px;width:65%;background:#000;border-radius:1px}.ios-bt-t{width:1.5px;height:4px;background:rgba(0,0,0,.35);border-radius:0 1px 1px 0}
.msg-hdr{display:flex;flex-direction:column;align-items:center;gap:3px;padding:2px 12px 7px;background:#F2F2F7;border-bottom:.5px solid rgba(0,0,0,.1);flex-shrink:0;position:relative}.msg-back{position:absolute;left:16px;color:#007AFF;font-size:17px;line-height:1}.msg-av{width:28px;height:28px;border-radius:50%;background:linear-gradient(135deg,#5AC8FA,#007AFF);display:flex;align-items:center;justify-content:center;font-size:12px;font-weight:600;color:#fff}.msg-name{font-size:10px;font-weight:600;color:#000}
.msgs{flex:1;padding:5px 10px 6px;display:flex;flex-direction:column;gap:3px;overflow-y:auto;background:#fff;scrollbar-width:none}.msgs::-webkit-scrollbar{display:none}.m{max-width:80%;padding:6px 10px;border-radius:16px;font-size:12px;line-height:1.35;letter-spacing:-.01em;margin-bottom:1px;flex-shrink:0;opacity:0;transform:translateY(8px)}.m.o{align-self:flex-end;background:#007AFF;color:#fff;border-radius:16px 16px 4px 16px}.m.i{align-self:flex-start;background:#E9E9EB;color:#000;border-radius:16px 16px 16px 4px}.m.v{animation:bub .3s ease forwards}.mt{text-align:center;font-size:8px;color:#8E8E93;padding:3px 0;flex-shrink:0}.md{text-align:right;font-size:8px;color:#8E8E93;padding:1px 4px 3px;flex-shrink:0}
.msg-in{display:flex;align-items:center;gap:5px;padding:5px 9px 16px;background:#F2F2F7;border-top:.5px solid rgba(0,0,0,.08);flex-shrink:0}.msg-field{flex:1;background:#fff;border-radius:16px;padding:6px 12px;font-size:11px;color:#C7C7CC;border:.5px solid rgba(0,0,0,.1)}.msg-send{width:22px;height:22px;border-radius:50%;background:#007AFF;display:flex;align-items:center;justify-content:center;font-size:13px;color:#fff;flex-shrink:0}.ios-home-i{display:flex;justify-content:center;padding:3px 0 2px;background:#F2F2F7;flex-shrink:0}.ios-home-bar{width:100px;height:4px;background:rgba(0,0,0,.12);border-radius:2px}@keyframes bub{to{opacity:1;transform:translateY(0)}}
.ent-dash{max-width:520px;margin:0 auto;background:var(--bg-surface);border-radius:16px;padding:22px 24px;animation:fu .8s var(--ease) .4s both}.ent-dash-hd{display:flex;justify-content:space-between;align-items:center;margin-bottom:16px;padding-bottom:14px;border-bottom:1px solid var(--border)}.ent-dash-title{font-weight:700;font-size:.85rem;color:var(--text-1)}.ent-dash-badge{font-size:.7rem;font-weight:600;padding:3px 9px;border-radius:99px;background:var(--accent-dim);color:var(--accent)}.ent-rows{display:flex;flex-direction:column;gap:8px}.ent-row{display:grid;grid-template-columns:34px 1fr auto auto;gap:10px;align-items:center;padding:10px 12px;border-radius:10px;background:var(--bg-alt);transition:background .5s var(--ease)}.ent-av{width:34px;height:34px;border-radius:50%;object-fit:cover}.ent-name{font-weight:600;font-size:.82rem;color:var(--text-1)}.ent-role{font-size:.7rem;color:var(--text-3)}.ent-task{font-size:.78rem;color:var(--text-2);font-style:italic}.ent-st{font-size:.7rem;font-weight:600;padding:3px 8px;border-radius:99px}.st-done{background:rgba(76,175,80,.1);color:#4caf50}.st-work{background:rgba(255,183,77,.1);color:#ffb74d}
.rotate-wrap{display:inline-block;position:relative;vertical-align:bottom}.rotate-word{display:inline-block;animation:ri .4s var(--ease) both;color:var(--accent);font-style:italic}@keyframes ri{from{opacity:0;transform:translateY(12px) rotateX(-30deg);filter:blur(2px)}to{opacity:1;transform:none;filter:blur(0)}}
.proof{padding:28px 24px;text-align:center;border-bottom:1px solid var(--border);transition:border-color .5s var(--ease)}.proof-inner{max-width:var(--max-w);margin:0 auto;display:flex;align-items:center;justify-content:center;gap:clamp(20px,4vw,48px);flex-wrap:wrap}.proof-item{display:flex;align-items:center;gap:8px}.proof-logo{height:20px;opacity:.4;transition:opacity .2s}.proof-logo:hover{opacity:.65}.proof-stat{font-weight:700;color:var(--text-2);font-size:.8rem}.proof-text{font-size:.76rem;color:var(--text-3);font-weight:500}
.lbl{font-size:.75rem;font-weight:600;letter-spacing:.1em;text-transform:uppercase;color:var(--accent);margin-bottom:10px;transition:color .5s var(--ease)}.sec-hd{text-align:center;margin-bottom:36px}.sec-hd h2{font-family:var(--font-display);font-size:clamp(1.4rem,2.8vw,2rem);font-weight:400;letter-spacing:-.02em;text-wrap:balance;transition:color .5s var(--ease)}
.steps{padding:64px 24px;background:var(--bg-alt);transition:background .5s var(--ease)}.steps-inner{max-width:var(--max-w);margin:0 auto}.steps-row{display:grid;grid-template-columns:repeat(4,1fr);gap:2px}.si{padding:28px 24px;background:var(--bg-surface);transition:background .5s var(--ease),transform .25s var(--ease)}.si:first-child{border-radius:14px 0 0 14px}.si:last-child{border-radius:0 14px 14px 0}.si:hover{transform:translateY(-2px)}.si-n{font-family:var(--font-display);font-size:1.8rem;color:var(--accent);opacity:.5;line-height:1;margin-bottom:12px}.si-t{font-weight:700;font-size:.82rem;letter-spacing:.03em;text-transform:uppercase;color:var(--text-1);margin-bottom:6px;transition:color .5s var(--ease)}.si-d{font-size:.84rem;line-height:1.5;color:var(--text-2);transition:color .5s var(--ease)}
.caps{padding:64px 24px}.caps-inner{max-width:var(--max-w);margin:0 auto}.caps-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:2px;border-radius:14px;overflow:hidden}.cap{padding:32px 28px;background:var(--bg-surface);transition:background .5s var(--ease),transform .25s var(--ease)}.cap:hover{transform:translateY(-2px)}.cap-title{font-family:var(--font-display);font-size:1.15rem;font-weight:400;margin-bottom:8px}.cap-desc{font-size:.84rem;line-height:1.55;color:var(--text-2)}
.pricing-section{padding:64px 24px;background:var(--bg-alt);transition:background .5s var(--ease)}.pricing-inner{max-width:var(--max-w);margin:0 auto}
.pg{display:grid;grid-template-columns:repeat(3,1fr);gap:2px;max-width:840px;margin:0 auto;border-radius:14px;overflow:hidden}.pc{background:var(--bg-surface);padding:32px 24px;display:flex;flex-direction:column;transition:background .5s var(--ease)}.pc.pop{background:var(--accent-dim)}.pc-t{font-size:.75rem;font-weight:700;letter-spacing:.06em;text-transform:uppercase;color:var(--text-2);margin-bottom:10px}.pc.pop .pc-t{color:var(--accent)}.pc-a{font-family:var(--font-display);font-size:2.4rem;line-height:1;color:var(--text-1);margin-bottom:4px}.pc-p{font-size:.8rem;color:var(--text-3);margin-bottom:20px}.pc-l{list-style:none;flex:1;margin-bottom:20px}.pc-l li{padding:6px 0;font-size:.84rem;color:var(--text-2)}.pc-l li+li{border-top:1px solid var(--border)}.pc-b{display:block;text-align:center;padding:11px;border-radius:99px;font-family:var(--font-body);font-size:.84rem;font-weight:600;text-decoration:none;border:1.5px solid var(--border);color:var(--text-1);background:transparent;cursor:pointer;margin-top:auto;transition:all .2s var(--ease)}.pc-b:hover{border-color:var(--accent);color:var(--accent)}.pc.pop .pc-b{background:var(--cta-bg);color:var(--cta-fg);border-color:var(--cta-bg)}.pc.pop .pc-b:hover{opacity:.88}
.trust-row{display:flex;justify-content:center;gap:clamp(24px,5vw,64px);flex-wrap:wrap;margin-top:36px}.ti{text-align:center}.ti strong{display:block;font-size:.85rem;font-weight:700;color:var(--text-1);margin-bottom:3px}.ti span{font-size:.78rem;color:var(--text-3)}
.cta-final{padding:72px 24px;text-align:center}.cta-final h2{font-family:var(--font-display);font-size:clamp(1.6rem,3.5vw,2.6rem);font-weight:400;letter-spacing:-.02em;margin-bottom:14px;text-wrap:balance}.cta-final p{color:var(--text-2);font-size:1rem;margin-bottom:28px}.cta-form{display:flex;gap:10px;max-width:400px;margin:0 auto 10px}.cta-form input{flex:1;padding:13px 18px;border:1px solid var(--border);border-radius:99px;background:var(--bg-surface);color:var(--text-1);font-family:var(--font-body);font-size:.9rem;outline:none;transition:all .3s var(--ease)}.cta-form input::placeholder{color:var(--text-3)}.cta-form input:focus{border-color:var(--accent)}.cta-note{font-size:.75rem;color:var(--text-3)}.cta-btns{display:flex;gap:12px;justify-content:center}
footer{padding:28px 24px;border-top:1px solid var(--border)}.fi{max-width:var(--max-w);margin:0 auto;display:flex;justify-content:space-between;align-items:center}.fl{display:flex;gap:24px;list-style:none}.fl a{font-size:.8rem;color:var(--text-3);text-decoration:none;transition:color .2s}.fl a:hover{color:var(--text-1)}.fn{font-size:.72rem;color:var(--text-3)}
.modal-overlay{position:fixed;inset:0;z-index:200;background:rgba(0,0,0,.5);backdrop-filter:blur(6px);display:flex;align-items:center;justify-content:center;padding:24px;animation:mb .25s ease}@keyframes mb{from{opacity:0}to{opacity:1}}.modal{background:var(--bg-surface);border-radius:20px;padding:36px 32px;max-width:400px;width:100%;text-align:center;animation:mi .3s var(--ease);border:1px solid var(--border)}@keyframes mi{from{opacity:0;transform:translateY(14px) scale(.97)}to{opacity:1;transform:none}}.modal h3{font-family:var(--font-display);font-size:1.4rem;font-weight:400;margin-bottom:6px}.modal p{font-size:.88rem;color:var(--text-2);margin-bottom:20px;line-height:1.5}.modal-form{display:flex;flex-direction:column;gap:8px}.modal-form input{padding:12px 16px;border:1px solid var(--border);border-radius:10px;background:var(--bg-alt);color:var(--text-1);font-family:var(--font-body);font-size:.9rem;outline:none}.modal-form input::placeholder{color:var(--text-3)}.modal-form input:focus{border-color:var(--accent)}.modal-form button{padding:12px;border-radius:10px;border:none;background:var(--cta-bg);color:var(--cta-fg);font-family:var(--font-body);font-size:.92rem;font-weight:600;cursor:pointer}.modal-close{margin-top:14px;background:none;border:none;color:var(--text-3);font-size:.82rem;cursor:pointer;font-family:var(--font-body)}.modal-close:hover{color:var(--text-1)}.modal-success{color:var(--accent);font-weight:600;font-size:.92rem;padding:16px 0}
.rv{opacity:0;transform:translateY(12px);transition:opacity .5s var(--ease),transform .5s var(--ease)}.rv.show{opacity:1;transform:none}
@media(max-width:860px){.hero h1{font-size:clamp(2rem,7vw,3rem)}.steps-row{grid-template-columns:repeat(2,1fr)}.si:first-child{border-radius:14px 0 0 0}.si:nth-child(2){border-radius:0 14px 0 0}.si:nth-child(3){border-radius:0 0 0 14px}.si:last-child{border-radius:0 0 14px 0}.caps-grid{grid-template-columns:1fr}.pg{grid-template-columns:1fr;max-width:360px}.iphone{width:230px;height:500px}}
@media(max-width:540px){.nav-btn{display:none}.steps-row{grid-template-columns:1fr}.si{border-radius:0!important}.si:first-child{border-radius:14px 14px 0 0!important}.si:last-child{border-radius:0 0 14px 14px!important}.proof-inner{flex-direction:column;gap:12px}.trust-row{flex-direction:column;gap:16px}.cta-form{flex-direction:column}.fi{flex-direction:column;gap:14px;text-align:center}.fl{flex-wrap:wrap;justify-content:center}}
@media(prefers-reduced-motion:reduce){*{transition-duration:0ms!important;animation-duration:0ms!important}.rv{opacity:1;transform:none}}
`;

const SU="https://script.google.com/macros/s/AKfycbwZZiYmxWfmUbsuJCYdxfEys8HihaCWUsw4r46OJ-DB1psv2kuqGWS2jeLfGpceZGcO/exec";

export default function Home(){
  const[mode,setMode]=useState<"personal"|"enterprise">("enterprise");
  const e=mode==="enterprise";
  const[showModal,setShowModal]=useState(false);
  const[modalDone,setModalDone]=useState(false);
  const openDemo=(ev:React.MouseEvent)=>{ev.preventDefault();setShowModal(true);setModalDone(false)};
  const submitDemo=(ev:React.FormEvent<HTMLFormElement>)=>{ev.preventDefault();const fd=new FormData(ev.currentTarget);fetch(SU,{method:"POST",body:JSON.stringify({name:fd.get("name"),email:fd.get("email"),company:fd.get("company"),type:"demo"})}).catch(()=>{});setModalDone(true);setTimeout(()=>{setShowModal(false);setModalDone(false)},2500)};
  const roles=["paralegal","research assistant","medical scribe","office manager","financial analyst"];
  const[roleIdx,setRoleIdx]=useState(0);
  useEffect(()=>{if(!e)return;const iv=setInterval(()=>setRoleIdx(i=>(i+1)%roles.length),2800);return()=>clearInterval(iv)},[e,roles.length]);
  useEffect(()=>{document.documentElement.setAttribute("data-mode",mode);document.title=e?"Everest":"Outdoors"},[mode,e]);
  useEffect(()=>{const f=()=>document.getElementById("nav")?.classList.toggle("scrolled",window.scrollY>20);window.addEventListener("scroll",f,{passive:true});return()=>window.removeEventListener("scroll",f)},[]);
  useEffect(()=>{const obs=new IntersectionObserver(es=>es.forEach(x=>{if(x.isIntersecting)x.target.classList.add("show")}),{threshold:0,rootMargin:"0px 0px 120px 0px"});document.querySelectorAll(".rv").forEach(el=>obs.observe(el));return()=>obs.disconnect()},[mode]);
  useEffect(()=>{if(e)return;const t=setTimeout(()=>{const ms=document.getElementById("waChat");if(!ms)return;const bs=ms.querySelectorAll(".m");if(bs[0]?.classList.contains("v"))return;bs.forEach((b,i)=>{setTimeout(()=>{b.classList.add("v");ms.scrollTop=ms.scrollHeight},i*400)})},300);return()=>clearTimeout(t)},[e]);
  const onSubmit=(ev:React.FormEvent<HTMLFormElement>)=>{ev.preventDefault();const inp=ev.currentTarget.querySelector("input") as HTMLInputElement;fetch(SU,{method:"POST",body:JSON.stringify({email:inp.value,type:"waitlist"})}).catch(()=>{});inp.value="";inp.placeholder="Thanks!";setTimeout(()=>{inp.placeholder="Your email"},3000)};
  const steps=e?[{l:"Connect",d:"Link your team\u2019s email, calendar, and files."},{l:"Assign",d:"Team members text what they need."},{l:"It works",d:"Opens their apps, drafts using their real files."},{l:"It\u2019s done",d:"Sent from their accounts. Actually done."}]:[{l:"Tell it",d:"Text or voice note what you need."},{l:"It logs in",d:"Opens your laptop and your real apps."},{l:"It works",d:"Writes the email, checks your calendar."},{l:"It\u2019s done",d:"Sent from your accounts. Actually done."}];
  const caps=e?[{t:"One dashboard",d:"Set up each employee in minutes. See everything from one place."},{t:"Uses their tools",d:"Gmail, Outlook, Drive, Slack. No new software."},{t:"Enterprise ready",d:"SSO, audit logs, permissions, dedicated support."}]:[{t:"Email",d:"Tell it who and what. Sent from your Gmail. Laptop never opened."},{t:"Calendar",d:"Books meetings, blocks focus time, resolves conflicts."},{t:"Documents",d:"Drafts proposals, applications, follow-ups from your files."}];
  return(<><style dangerouslySetInnerHTML={{__html:css}}/>
  <nav id="nav"><a href="#" className="logo">{e?"EVEREST":"outdoors"}</a><div className="pill"><button className={!e?"on":""} onClick={()=>setMode("personal")}>Personal</button><button className={e?"on":""} onClick={()=>setMode("enterprise")}>Enterprise</button></div>{e?<button className="nav-btn" onClick={openDemo}>Request Demo</button>:<a href="#cta" className="nav-btn">Join Waitlist</a>}</nav>
  <section className="hero">
    <h1>{e?<>Another <span className="rotate-wrap"><span className="rotate-word" key={roleIdx}>{roles[roleIdx]}</span></span> for a fraction of the cost.</>:<>Your to-do list, <em>actually done.</em></>}</h1>
    <p className="hero-sub">{e?"Give every employee an assistant that uses their computer for them. Email, calendar, documents, through the tools you already have.":"Text what you need. It opens your laptop, logs into your apps, and does it. Email sent. Meeting booked. You never sat down."}</p>
    <div className="hero-ctas">{e?<button className="btn-primary" onClick={openDemo}>Request a Demo</button>:<a href="#cta" className="btn-primary">Join Waitlist</a>}<a href={e?"#pricing":"#steps"} className="btn-text">{e?"See pricing":"How it works"}</a></div>
    {e&&<div className="ent-dash"><div className="ent-dash-hd"><div className="ent-dash-title">Team Activity</div><div className="ent-dash-badge">3 assistants active</div></div><div className="ent-rows">{[{img:"photo-1559839734-2b71ea197ec2",n:"Dr. Sarah Kim",r:"Dentist, Kim Family Dental",task:"Patient follow-ups",st:"Sent",cls:"st-done"},{img:"photo-1507003211169-0a1dd7228f2d",n:"James Okafor",r:"Paralegal, Reed & Associates",task:"Case brief draft",st:"Working",cls:"st-work"},{img:"photo-1580489944761-15a19d654956",n:"Maria Reyes",r:"Analyst, Vanguard Capital",task:"Quarterly report",st:"Sent",cls:"st-done"}].map(r=><div key={r.n} className="ent-row"><img className="ent-av" src={`https://images.unsplash.com/${r.img}?w=68&h=68&fit=crop&crop=face`} alt=""/><div><div className="ent-name">{r.n}</div><div className="ent-role">{r.r}</div></div><div className="ent-task">{r.task}</div><div className={`ent-st ${r.cls}`}>{r.st}</div></div>)}</div></div>}
    {!e&&<div className="phone-wrap"><div className="iphone"><div className="iphone-screen"><div className="di"/><div className="ios-bar"><div className="ios-time">9:15</div><div className="ios-icons"><div className="ios-sig"><span/><span/><span/><span/></div><div className="ios-bt"><div className="ios-bt-b"><div className="ios-bt-f"/></div><div className="ios-bt-t"/></div></div></div><div className="msg-hdr"><span className="msg-back">&lsaquo;</span><div className="msg-av">O</div><div className="msg-name">Outdoors</div></div><div className="msgs" id="waChat"><div className="mt">Today 9:14 AM</div><div className="m o">Email the team I{"'"}ll be 15 min late. Keep it casual.</div><div className="md">Delivered</div><div className="m i">Done. Sent from your Gmail: {"\u201c"}Running ~15 min behind. Start without me.{"\u201d"}</div><div className="m o">Anything after 3pm? If not, block it for deep work.</div><div className="mt">Read 9:14 AM</div><div className="m i">Clear after 3. Blocked 3{"\u2013"}5:30 PM. Do Not Disturb on.</div><div className="m o">Build me a landing page.</div><div className="mt">Read 9:15 AM</div><div className="m i">You{"'"}re looking at it.</div></div><div className="msg-in"><div className="msg-field">Message</div><div className="msg-send">+</div></div><div className="ios-home-i"><div className="ios-home-bar"/></div></div></div></div>}
  </section>
  <div className="proof"><div className="proof-inner"><div className="proof-item"><img className="proof-logo" src="https://upload.wikimedia.org/wikipedia/commons/thumb/b/b5/Rice_University_wordmark.svg/200px-Rice_University_wordmark.svg.png" alt="Rice University"/></div><div className="proof-item"><span className="proof-stat">5 users</span><span className="proof-text">in 3 days</span></div><div className="proof-item"><span className="proof-stat">40%</span><span className="proof-text">conversion</span></div><div className="proof-item"><span className="proof-stat">2 paying</span><span className="proof-text">day one</span></div></div></div>
  <section className="steps" id="steps"><div className="steps-inner"><div className="sec-hd rv"><div className="lbl">How it works</div><h2>{e?"Set up once. Help forever.":"You talk. It does."}</h2></div><div className="steps-row">{steps.map((s,i)=><div key={s.l} className="si rv" style={{transitionDelay:`${i*50}ms`}}><div className="si-n">0{i+1}</div><div className="si-t">{s.l}</div><p className="si-d">{s.d}</p></div>)}</div></div></section>
  <section className="caps"><div className="caps-inner"><div className="sec-hd rv"><div className="lbl">What it does</div><h2>{e?"Everything your team wastes time on.":"The work you never get to."}</h2></div><div className="caps-grid">{caps.map((c,i)=><div key={c.t} className="cap rv" style={{transitionDelay:`${i*50}ms`}}><div className="cap-title">{c.t}</div><p className="cap-desc">{c.d}</p></div>)}</div></div></section>
  <section className="pricing-section" id="pricing"><div className="pricing-inner"><div className="sec-hd rv"><div className="lbl">Pricing</div><h2>{e?"Tailored to your team.":"Simple pricing."}</h2></div>
    {!e?<div className="pg">{[{t:"Free",a:"$0",p:"per month",pop:false,f:["Bring your own API key","Core assistant","Email + calendar","Community support"],b:"Get Started"},{t:"Pro",a:"$30",p:"per month",pop:true,f:["No API key needed","All features","Priority execution","Email support"],b:"Join Waitlist"},{t:"Premium",a:"$100",p:"per month",pop:false,f:["Unlimited usage","Custom integrations","Phone support","Early access"],b:"Join Waitlist"}].map(c=><div key={c.t} className={`pc ${c.pop?"pop":""}`}><div className="pc-t">{c.t}</div><div className="pc-a">{c.a}</div><div className="pc-p">{c.p}</div><ul className="pc-l">{c.f.map(f=><li key={f}>{f}</li>)}</ul><a href="#cta" className="pc-b">{c.b}</a></div>)}</div>
    :<div style={{maxWidth:440,margin:"0 auto"}}><div className="pc pop" style={{borderRadius:14}}><div className="pc-t">Enterprise</div><div className="pc-a" style={{fontSize:"1.8rem"}}>Custom</div><div className="pc-p">priced per team, based on your needs</div><ul className="pc-l"><li>One assistant per employee</li><li>Admin dashboard and analytics</li><li>Works with all your existing tools</li><li>Custom workflows and integrations</li><li>Dedicated onboarding and support</li><li>SLA guarantee</li></ul><button className="pc-b" onClick={openDemo}>Request a Demo</button></div></div>}
    <div className="trust-row"><div className="ti"><strong>Runs locally</strong><span>Your machine, your credentials</span></div><div className="ti"><strong>Zero data retention</strong><span>Nothing stored on our servers</span></div><div className="ti"><strong>End-to-end encrypted</strong><span>All communications secured</span></div>{e&&<div className="ti"><strong>Enterprise controls</strong><span>SSO, audit logs, permissions</span></div>}</div>
  </div></section>
  <section className="cta-final" id="cta">{!e?<><h2 className="rv">Stop organizing. Start doing.</h2><p className="rv">Join the waitlist for early access.</p><form className="cta-form rv" onSubmit={onSubmit}><input type="email" placeholder="Your email" required/><button type="submit" className="btn-primary">Join Waitlist</button></form><div className="cta-note rv">Free to start. No credit card.</div></>:<><h2 className="rv">Give your team superpowers.</h2><p className="rv">See how Everest saves your team 30+ hours a week.</p><div className="cta-btns rv"><button className="btn-primary" onClick={openDemo}>Request a Demo</button><button className="btn-text" onClick={openDemo}>Contact Sales</button></div></>}</section>
  <footer><div className="fi"><span className="logo">{e?"EVEREST":"outdoors"}</span><ul className="fl"><li><a href="#steps">Product</a></li><li><a href="#pricing">Pricing</a></li></ul><span className="fn">Built at Rice University</span></div></footer>
  {showModal&&<div className="modal-overlay" onClick={()=>setShowModal(false)}><div className="modal" onClick={ev=>ev.stopPropagation()}>{!modalDone?<><h3>Request a demo</h3><p>Leave your email and we{"'"}ll schedule a walkthrough.</p><form className="modal-form" onSubmit={submitDemo}><input type="text" name="name" placeholder="Your name" required/><input type="email" name="email" placeholder="Work email" required/><input type="text" name="company" placeholder="Company name"/><button type="submit">Submit</button></form><button className="modal-close" onClick={()=>setShowModal(false)}>Maybe later</button></>:<div className="modal-success">Thanks! We{"'"}ll be in touch shortly.</div>}</div></div>}
  </>)
}
